apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Fio
metadata:
  name: fio-sample
spec:
  image:
    name: xridge/fio:latest
    pullPolicy: Always
    # pullSecret: null

  # builtinJobFiles:
  #  - /jobs/rand-read.fio
  #  - /jobs/rand-write.fio

  cmdLineArgs: --name=randwrite --iodepth=1 --rw=randwrite --bs=4m --direct=1 --size=256M --numjobs=1
